In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("movies.csv")

In [2]:
data.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [3]:
df = data[['title_x','genres','summary']]
df.head()

,title_x,genres,summary
0,Uri: The Surgical Strike,Action|Drama|War,Indian army special forces execute a covert op...
1,Battalion 609,War,The story of Battalion 609 revolves around a c...
2,The Accidental Prime Minister (film),Biography|Drama,Explores Manmohan Singh's tenure as the Prime ...
3,Why Cheat India,Crime|Drama,The movie focuses on existing malpractices in ...
4,Evening Shadows,Drama,Under the 'Evening Shadows' truth often plays...

Preprocessing starts

Lowercasing

In [4]:
df['title_x']=df['title_x'].str.lower()
df['genres']=df['genres'].str.lower()
df['summary']=df['summary'].str.lower()
df.head()

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_16416\4042318090.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title_x']=df['title_x'].str.lower()
C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_16416\4042318090.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres']=df['genres'].str.lower()
C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_16416\4042318090.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['summary']=df['summary'].str.lower()

,title_x,genres,summary
0,uri: the surgical strike,action|drama|war,indian army special forces execute a covert op...
1,battalion 609,war,the story of battalion 609 revolves around a c...
2,the accidental prime minister (film),biography|drama,explores manmohan singh's tenure as the prime ...
3,why cheat india,crime|drama,the movie focuses on existing malpractices in ...
4,evening shadows,drama,under the 'evening shadows' truth often plays...

Removing Punctuation

In [5]:
import string
punctuations = string.punctuation
print(punctuations)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [10]:
def remove_punc(text):
    newsent = []
    for word in text.split():
        if word in punctuations:
            newsent.append("")
        else :
            newsent.append(word)
    return " ".join(newsent)

In [14]:
df['title_x']=df['title_x'].apply(remove_punc)
df['summary']=df['summary'].apply(remove_punc)

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_16416\1714062054.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title_x']=df['title_x'].apply(remove_punc)
C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_16416\1714062054.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['summary']=df['summary'].apply(remove_punc)

In [16]:
df['summary']

0       indian army special forces execute a covert op...
1       the story of battalion 609 revolves around a c...
2       explores manmohan singh's tenure as the prime ...
3       the movie focuses on existing malpractices in ...
4       under the 'evening shadows' truth often plays ...
                              ...
1624    a man is torn between his handicapped brother ...
1625    a singer finds out she was adopted when the ed...
1626    village born lalloo re-locates to bombay and r...
1627    shinda tries robbing a bank so he can be wealt...
1628    ashar and khirad are forced to get married due...
Name: summary, Length: 1629, dtype: object