In [4]:
import numpy as np 
import pandas as pd

In [6]:
data= pd.read_csv('IMDB Dataset.csv')
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

Preprocessing Stage

In [29]:
df = data.iloc[1:1500:]
df.shape

(1499, 2)

In [30]:
df.head()

                                              review sentiment
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive

Lowercasing

In [31]:
df['review'] = df['review'].str.lower()
df.head()

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_12264\1300440577.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].str.lower()

                                              review sentiment
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive
5  probably my all-time favorite movie, a story o...  positive

Removing HTML Tags

In [32]:
import re

def remove_html_tagsre(text):
    clean = re.compile(r'<.*?>', re.DOTALL)
    return re.sub(clean, '', text)

df['review'] = df['review'].apply(remove_html_tagsre)
df.head()

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_12264\355156253.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_html_tagsre)

                                              review sentiment
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive
5  probably my all-time favorite movie, a story o...  positive

Removing Punctuation

In [33]:
import string
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [34]:
# def remove_punc(text):
#     word = []
#     for i in text.split():
#         if i in exclude:
#             word.append("")
#         else:
#             word.append(i)

# takes a lot of time so we apply this

def removepunc(text):
    return text.translate(str.maketrans('','',exclude))

In [35]:
df['review'] = df['review'].apply(removepunc)
df.head()

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_12264\1535469917.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(removepunc)

                                              review sentiment
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive
5  probably my alltime favorite movie a story of ...  positive

Removing Stopwords

In [36]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
print(list(stop_words))

["he's", 'these', 'do', 'wouldn', 'your', 'did', "they've", 'than', 'y', "we're", 'own', 'further', "we've", 'o', "didn't", 'with', "aren't", 'down', 'then', "i've", 'after', 'again', 'when', 'itself', 'ours', 'it', 'were', 'until', 'how', 'not', 'so', 'if', 'their', 'doesn', 'while', 'has', 's', 'here', "shouldn't", 'during', 'wasn', 'who', 'm', 'from', 'his', "don't", 'can', 'or', 'they', "you'll", 'am', 'won', 'be', 'by', 'couldn', 'why', 'the', 'for', "she's", 'ourselves', 'been', 'of', 'he', 'other', 'aren', 're', "they'd", 'are', 'as', 'but', "he'd", 'only', 'is', 'yourself', 'yours', 'mightn', 'any', 'under', "it's", 'just', 'very', "i'd", 'now', 'hadn', 'into', "should've", 't', "we'd", 'was', 'both', 'had', 'those', 'at', "wasn't", 'against', 'hers', "i'm", "you've", 'its', 'up', 'she', 'themselves', 'over', "isn't", "mightn't", 'her', 'our', 'and', 'myself', "they're", "haven't", 'needn', 'me', 'such', 'mustn', 'on', "we'll", 'you', "wouldn't", 'd', "that'll", 'my', "she'll", 've', 'all', 'theirs', 'no', "needn't", 'him', 'having', "it'll", 'herself', 'same', 'doing', 'does', "hadn't", 'them', 'didn', "she'd", 'where', "i'll", 'ma', "doesn't", 'yourselves', 'a', "it'd", 'we', 'about', 'some', "weren't", 'whom', 'ain', 'above', 'in', 'through', "mustn't", 'out', 'have', 'an', "you'd", 'don', 'nor', 'weren', 'more', "hasn't", 'should', 'off', 'because', "they'll", 'once', 'which', 'what', 'few', 'most', 'hasn', 'will', 'll', 'to', "couldn't", 'there', 'being', 'below', "you're", 'too', 'this', 'i', 'that', 'each', "shan't", 'between', 'isn', 'haven', 'himself', 'before', 'shan', "he'll", 'shouldn', "won't"]

In [39]:
# def remove_stopwords(text):
#     new_text = []
#     for word in text.split():
#         if word in stopwords.words('english'):
#             new_text.append("")
#         else:
#             new_text.append(word)
    
#     return " ".join(new_text)

# faster  way
from nltk.corpus import stopwords

# Preload stopwords once
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    # Split and filter using set membership
    return " ".join(word for word in text.split() if word not in stop_words)

In [40]:
df['review'] = df['review'].astype(str).apply(remove_stopwords)

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_12264\2045759792.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].astype(str).apply(remove_stopwords)

In [41]:
df.head()

                                              review sentiment
1  wonderful little production filming technique ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive
5  probably alltime favorite movie story selfless...  positive

Find out the number of words in the entire corpus

In [ ]:
words = []
for review in df['review']:
    for word in review.split():
        words.append(word)
len(words)

174560

the total number of unique words(vocabulary) using just python

In [45]:
unique = set(words)
unli = list(unique)
len(unli)

26480

Apply bag words and find the vocabulary also find the times each word has occured

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cnv = CountVectorizer()
bow = cnv.fit_transform(df['review'])
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

bow.toarray().shape

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]

(1499, 26433)

In [52]:
cnv.vocabulary_

{'wonderful': 26022,
 'little': 13818,
 'production': 18296,
 'filming': 8799,
 'technique': 23298,
 'unassuming': 24486,
 'oldtimebbc': 16457,
 'fashion': 8545,
 'gives': 9877,
 'comforting': 4802,
 'sometimes': 21790,
 'discomforting': 6695,
 'sense': 20769,
 'realism': 18951,
 'entire': 7859,
 'piece': 17566,
 'actors': 603,
 'extremely': 8362,
 'well': 25641,
 'chosen': 4335,
 'michael': 14907,
 'sheen': 21016,
 'got': 10084,
 'polari': 17842,
 'voices': 25291,
 'pat': 17151,
 'truly': 24289,
 'see': 20632,
 'seamless': 20574,
 'editing': 7433,
 'guided': 10355,
 'references': 19129,
 'williams': 25875,
 'diary': 6517,
 'entries': 7875,
 'worth': 26123,
 'watching': 25517,
 'terrificly': 23400,
 'written': 26172,
 'performed': 17364,
 'masterful': 14513,
 'one': 16491,
 'great': 10202,
 'masters': 14525,
 'comedy': 4782,
 'life': 13654,
 'really': 18963,
 'comes': 4796,
 'home': 11233,
 'things': 23574,
 'fantasy': 8508,
 'guard': 10333,
 'rather': 18879,
 'use': 24918,
 'traditional': 24062,
 'dream': 7125,
 'techniques': 23299,
 'remains': 19286,
 'solid': 21755,
 'disappears': 6661,
 'plays': 17726,
 'knowledge': 13124,
 'senses': 20773,
 'particularly': 17100,
 'scenes': 20384,
 'concerning': 4988,
 'orton': 16672,
 'halliwell': 10507,
 'sets': 20869,
 'flat': 8975,
 'halliwells': 10508,
 'murals': 15608,
 'decorating': 6125,
 'every': 8081,
 'surface': 22902,
 'terribly': 23397,
 'done': 6971,
 'thought': 23645,
 'way': 25546,
 'spend': 21998,
 'time': 23767,
 'hot': 11372,
 'summer': 22823,
 'weekend': 25616,
 'sitting': 21379,
 'air': 890,
 'conditioned': 5015,
 'theater': 23471,
 'lighthearted': 13690,
 'plot': 17760,
 'simplistic': 21315,
 'dialogue': 6506,
 'witty': 25981,
 'characters': 4121,
 'likable': 13702,
 'even': 8052,
 'bread': 3206,
 'suspected': 22956,
 'serial': 20826,
 'killer': 13030,
 'may': 14593,
 'disappointed': 6663,
 'realize': 18957,
 'match': 14536,
 'point': 17812,
 'risk': 19777,
 'addiction': 638,
 'proof': 18373,
 'woody': 26043,
 'allen': 1011,
 'still': 22387,
 'fully': 9461,
 'control': 5220,
 'style': 22661,
 'many': 14380,
 'us': 24911,
 'grown': 10309,
 'lovethis': 14036,
 'id': 11599,
 'laughed': 13398,
 'woodys': 26044,
 'comedies': 4781,
 'years': 26261,
 'dare': 5919,
 'say': 20326,
 'decade': 6077,
 'ive': 12516,
 'never': 15928,
 'impressed': 11790,
 'scarlet': 20362,
 'johanson': 12712,
 'managed': 14307,
 'tone': 23920,
 'sexy': 20918,
 'image': 11687,
 'jumped': 12836,
 'right': 19726,
 'average': 1965,
 'spirited': 22031,
 'young': 26317,
 'womanthis': 26014,
 'crown': 5654,
 'jewel': 12658,
 'career': 3764,
 'wittier': 25978,
 'devil': 6474,
 'wears': 25592,
 'prada': 18042,
 'interesting': 12214,
 'superman': 22863,
 'go': 9948,
 'friends': 9381,
 'basically': 2280,
 'theres': 23538,
 'family': 8478,
 'boy': 3128,
 'jake': 12548,
 'thinks': 23587,
 'zombie': 26404,
 'closet': 4581,
 'parents': 17056,
 'fighting': 8756,
 'timethis': 23813,
 'movie': 15458,
 'slower': 21569,
 'soap': 21695,
 'opera': 16568,
 'suddenly': 22772,
 'decides': 6104,
 'become': 2385,
 'rambo': 18797,
 'kill': 13026,
 'zombieok': 26407,
 'first': 8903,
 'youre': 26328,
 'going': 9986,
 'make': 14262,
 'film': 8775,
 'must': 15653,
 'decide': 6101,
 'thriller': 23674,
 'drama': 7095,
 'watchable': 25505,
 'divorcing': 6879,
 'arguing': 1574,
 'like': 13704,
 'real': 18945,
 'totally': 24004,
 'ruins': 20067,
 'expected': 8252,
 'boogeyman': 2995,
 'similar': 21301,
 'instead': 12146,
 'watched': 25509,
 'meaningless': 14678,
 'spots3': 22105,
 '10': 5,
 'playing': 17723,
 'descent': 6360,
 'dialogs': 6504,
 'shots': 21145,
 'ignore': 11651,
 'petter': 17464,
 'matteis': 14564,
 'love': 14011,
 'money': 15257,
 'visually': 25258,
 'stunning': 22634,
 'watch': 25503,
 'mr': 15536,
 'mattei': 14563,
 'offers': 16392,
 'vivid': 25270,
 'portrait': 17937,
 'human': 11461,
 'relations': 19235,
 'seems': 20647,
 'telling': 23333,
 'power': 18026,
 'success': 22746,
 'people': 17312,
 'different': 6563,
 'situations': 21381,
 'encounter': 7714,
 'variation': 25015,
 'arthur': 1653,
 'schnitzlers': 20426,
 'play': 17714,
 'theme': 23488,
 'director': 6637,
 'transfers': 24110,
 'action': 589,
 'present': 18153,
 'new': 15934,
 'york': 26301,
 'meet': 14722,
 'connect': 5070,
 'connected': 5071,
 'another': 1335,
 'next': 15954,
 'person': 17415,
 'know': 13117,
 'previous': 18204,
 'contact': 5143,
 'stylishly': 22667,
 'sophisticated': 21822,
 'luxurious': 14138,
 'look': 13928,
 'taken': 23139,
 'live': 13822,
 'world': 26087,
 'habitatthe': 10438,
 'thing': 23570,
 'gets': 9794,
 'souls': 21858,
 'picture': 17557,
 'stages': 22177,
 'loneliness': 13902,
 'inhabits': 12032,
 'big': 2627,
 'city': 4427,
 'exactly': 8128,
 'best': 2563,
 'place': 17665,
 'find': 8856,
 'sincere': 21329,
 'fulfillment': 9455,
 'discerns': 6686,
 'case': 3860,
 'encounterthe': 7718,
 'acting': 582,
 'good': 10019,
 'direction': 6627,
 'steve': 22366,
 'buscemi': 3497,
 'rosario': 19965,
 'dawson': 5983,
 'carol': 3809,
 'kane': 12887,
 'imperioli': 11753,
 'adrian': 702,
 'grenier': 10237,
 'rest': 19531,
 'talented': 23148,
 'cast': 3884,
 'come': 4774,
 'alivewe': 996,
 'wish': 25948,
 'luck': 14084,
 'await': 1984,
 'anxiously': 1406,
 'work': 26062,
 'probably': 18266,
 'alltime': 1042,
 'favorite': 8601,
 'story': 22472,
 'selflessness': 20708,
 'sacrifice': 20134,
 'dedication': 6134,
 'noble': 16033,
 'cause': 3946,
 'preachy': 18065,
 'boring': 3057,
 'old': 16444,
 'despite': 6402,
 'seen': 20649,
 '15': 50,
 'times': 23794,
 'last': 13355,
 '25': 226,
 'paul': 17198,
 'lukas': 14099,
 'performance': 17356,
 'brings': 3275,
 'tears': 23286,
 'eyes': 8382,
 'bette': 2592,
 'davis': 5978,
 'sympathetic': 23064,
 'roles': 19889,
 'delight': 6215,
 'kids': 13017,
 'grandma': 10157,
 'says': 20332,
 'dressedup': 7147,
 'midgets': 14948,
 'children': 4268,
 'makes': 14268,
 'fun': 9468,
 'mothers': 15404,
 'slow': 21567,
 'awakening': 1991,
 'whats': 25722,
 'happening': 10599,
 'roof': 19935,
 'believable': 2465,
 'startling': 22269,
 'dozen': 7071,
 'thumbs': 23709,
 'theyd': 23555,
 'sure': 22898,
 'would': 26131,
 'resurrection': 19563,
 'dated': 5959,
 'seahunt': 20571,
 'series': 20829,
 'tech': 23293,
 'today': 23868,
 'bring': 3273,
 'back': 2066,
 'kid': 13000,
 'excitement': 8177,
 'mei': 14739,
 'grew': 10239,
 'black': 2728,
 'white': 25788,
 'tv': 24361,
 'gunsmoke': 10389,
 'heros': 10970,
 'weekyou': 25621,
 'vote': 25316,
 'comeback': 4775,
 'sea': 20565,
 'huntwe': 11519,
 'need': 15844,
 'change': 4077,
 'pace': 16913,
 'water': 25522,
 'adventureoh': 724,
 'thank': 23446,
 'outlet': 16749,
 'view': 25157,
 'viewpoints': 25171,
 'moviesso': 15511,
 'ole': 16459,
 'believe': 2469,
 'wanna': 25427,
 'saywould': 20335,
 'nice': 15961,
 'read': 18930,
 'plus': 17789,
 'points': 17827,
 'huntif': 11513,
 'rhymes': 19675,
 'lines': 13753,
 'let': 13586,
 'submitor': 22704,
 'leave': 13486,
 'doubt': 7031,
 'quitif': 18697,
 'lets': 13592,
 'show': 21158,
 'amazing': 1127,
 'fresh': 9365,
 'innovative': 12074,
 'idea': 11600,
 '70s': 345,
 'aired': 895,
 'brilliant': 3263,
 'dropped': 7189,
 '1990': 170,
 'funny': 9491,
 'anymore': 1410,
 'continued': 5182,
 'decline': 6118,
 'complete': 4912,
 'waste': 25498,
 'todayits': 23871,
 'disgraceful': 6732,
 'far': 8511,
 'fallen': 8463,
 'writing': 26170,
 'painfully': 16949,
 'bad': 2093,
 'performances': 17358,
 'almost': 1059,
 'mildly': 14973,
 'entertaining': 7843,
 'respite': 19518,
 'guesthosts': 10348,
 'wouldnt': 26133,
 'hard': 10620,
 'creator': 5529,
 'handselected': 10565,
 'original': 16654,
 'also': 1077,
 'chose': 4334,
 'band': 2183,
 'hacks': 10447,
 'followed': 9121,
 'recognize': 19033,
 'brilliance': 3262,
 'fit': 8926,
 'replace': 19391,
 'mediocrity': 14709,
 'felt': 8671,
 'give': 9874,
 'stars': 22254,
 'respect': 19507,
 'made': 14196,
 'huge': 11446,
 'awful': 2013,
 'cant': 3705,
 'encouraged': 7720,
 'positive': 17957,
 'comments': 4830,
 'looking': 13936,
 'forward': 9245,
 'mistake': 15151,
 '950': 396,
 'films': 8819,
 'worst': 26122,
 'pacing': 16921,
 'storyline': 22479,
 'soundtrack': 21866,
 'song': 21801,
 'lame': 13278,
 'country': 5395,
 'tune': 24325,
 'played': 17719,
 'less': 13572,
 'four': 9264,
 'looks': 13940,
 'cheap': 4184,
 'nasty': 15778,
 'extreme': 8360,
 'rarely': 18865,
 'happy': 10608,
 'end': 7725,
 'credits': 5542,
 'prevents': 18200,
 'giving': 9879,
 '1score': 189,
 'harvey': 10687,
 'keitel': 12946,
 'least': 13482,
 'making': 14273,
 'bit': 2704,
 'effort': 7473,
 'obsessives': 16320,
 'gut': 10402,
 'wrenching': 26155,
 'laughter': 13407,
 'hell': 10885,
 'mom': 15237,
 'liked': 13707,
 'itgreat': 12472,
 'camp': 3655,
 'phil': 17487,
 'alien': 974,
 'quirky': 18694,
 'humour': 11489,
 'based': 2271,
 'around': 1618,
 'oddness': 16367,
 'everything': 8091,
 'actual': 610,
 'punchlinesat': 18545,
 'odd': 16361,
 'pretty': 18192,
 'progressed': 18331,
 'didnt': 6541,
 'jokes': 12732,
 'anymoreits': 1411,
 'low': 14041,
 'budget': 3393,
 'thats': 23467,
 'problem': 18267,
 'eventually': 8061,
 'lost': 13980,
 'interesti': 12213,
 'imagine': 11699,
 'appeal': 1472,
 'stoner': 22445,
 'currently': 5762,
 'partakingfor': 17086,
 'something': 21783,
 'better': 2593,
 'try': 24304,
 'brother': 3331,
 'planet': 17687,
 'saw': 20324,
 '12': 31,
 'came': 3638,
 'recall': 19004,
 'scariest': 20360,
 'scene': 20375,
 'bird': 2685,
 'eating': 7392,
 'men': 14781,
 'dangling': 5897,
 'helplessly': 10906,
 'parachutes': 17026,
 'horror': 11340,
 'horroras': 11342,
 'cheesy': 4218,
 'saturday': 20300,
 'afternoons': 792,
 'tired': 23837,
 'formula': 9216,
 'monster': 15293,
 'type': 24423,
 'movies': 15502,
 'usually': 24939,
 'included': 11863,
 'hero': 10961,
 'beautiful': 2367,
 'woman': 26004,
 'might': 14959,
 'daughter': 5964,
 'professor': 18314,
 'resolution': 19493,
 'died': 6546,
 'care': 3761,
 'much': 15554,
 'romantic': 19912,
 'angle': 1274,
 'year': 26256,
 'predictable': 18094,
 'plots': 17769,
 'unintentional': 24682,
 'humorbut': 11483,
 'later': 13374,
 'psycho': 18481,
 'loved': 14015,
 'star': 22236,
 'janet': 12564,
 'leigh': 13524,
 'bumped': 3449,
 'early': 7356,
 'sat': 20276,
 'took': 23947,
 'notice': 16165,
 'since': 21328,
 'screenwriters': 20528,
 'scary': 20366,
 'possible': 17973,
 'wellworn': 25679,
 'rules': 20072,
 'im': 11686,
 'fan': 8488,
 'bolls': 2954,
 'enjoyed': 7804,
 'postal': 17980,
 'maybe': 14595,
 'boll': 2953,
 'apparently': 1471,
 'bought': 3098,
 'rights': 19738,
 'cry': 5689,
 'long': 13908,
 'ago': 844,
 'game': 9588,
 'finsished': 8887,
 'killing': 13033,
 'mercs': 14822,
 'infiltrating': 11998,
 'secret': 20611,
 'research': 19457,
 'labs': 13230,
 'located': 13862,
 'tropical': 24266,
 'island': 12406,
 'warned': 25461,
 'schemed': 20407,
 'together': 23880,
 'along': 1064,
 'legion': 13516,
 'schmucks': 20423,
 'feeling': 8653,
 'loneley': 13901,
 'set': 20863,
 'invites': 12338,
 'three': 23664,
 'countrymen': 5397,
 'players': 17721,
 'names': 15736,
 'til': 23756,
 'schweiger': 20446,
 'udo': 24444,
 'kier': 13021,
 'ralf': 18788,
 'moellerthree': 15221,
 'actually': 612,
 'selfs': 20717,
 'biz': 2721,
 'tale': 23146,
 'goes': 9981,
 'jack': 12526,
 'carver': 3853,
 'yes': 26282,
 'german': 9779,
 'hail': 10465,
 'bratwurst': 3187,
 'dudes': 7232,
 'however': 11412,
 'tils': 23761,
 'badass': 2096,
 'complained': 4902,
 'hes': 10983,
 'staying': 22303,
 'true': 24285,
 'whole': 25799,
 'agenda': 828,
 'perspective': 17428,
 'dont': 6989,
 'looked': 13933,
 'kicking': 12997,
 'beyond': 2609,
 'demented': 6250,
 'evil': 8105,
 'mad': 14188,
 'scientist': 20454,
 'dr': 7075,
 'krieger': 13171,
 'geneticallymutatedsoldiers': 9737,
 'gms': 9943,
 'called': 3621,
 'performing': 17368,
 'topsecret': 23972,
 'reminds': 19314,
 'spoiler': 22063,
 'vancouver': 24998,
 'reason': 18980,
 'palm': 16985,
 'trees': 24190,
 'rich': 19686,
 'lumberjackwoods': 14107,
 'havent': 10730,
 'gone': 10013,
 'started': 22263,
 'mehehe': 14736,
 'cannot': 3700,
 'stay': 22300,
 'shenanigans': 21041,
 'delivers': 6228,
 'experience': 8263,
 'meaning': 14675,
 'suckthere': 22770,
 'mentioning': 14804,
 'imply': 11775,
 'areas': 1564,
 'boat': 2901,
 'cromedalbino': 5621,
 'squad': 22140,
 'enters': 7838,
 'laugh': 13392,
 'reeks': 19115,
 'scheisse': 20404,
 'poop': 17894,
 'simpletons': 21312,
 'take': 23137,
 'wiff': 25844,
 'ahead': 867,
 'btw': 3376,
 'annoying': 1323,
 'sidekick': 21235,
 'shoot': 21108,
 'minutes': 15079,
 'screen': 20512,
 'shakespeareshakespeare': 20950,
 'losti': 13981,
 'appreciate': 1500,
 'trying': 24305,
 'shakespeare': 20946,
 'masses': 14504,
 'ruin': 20064,
 'goodis': 10030,
 'scottish': 20481,
 'certain': 4031,
 'rev': 19602,
 'bowdler': 3109,
 'hence': 10913,
 'bowdlerization': 3110,
 'tried': 24225,
 'victorian': 25144,
 'erain': 7928,
 'words': 26059,
 'improve': 11804,
 'perfectioni': 17348,
 'write': 26163,
 'ten': 23355,
 'text': 23433,
 'english': 7786,
 'composition': 4939,
 'forte': 9227,
 'keep': 12939,
 'saying': 20329,
 'cut': 5792,
 'fantastic': 8503,
 'prisoners': 18253,
 'famous': 8486,
 'george': 9766,
 'clooney': 4571,
 'roll': 19898,
 'man': 14305,
 'constant': 5124,
 'sorrow': 21838,
 'recommand': 19039,
 'everybody': 8083,
 'greetings': 10231,
 'bart': 2266,
 'kind': 13045,
 'drawn': 7117,
 'erotic': 7952,
 'amateurish': 1117,
 'unbelievable': 24496,
 'bits': 2713,
 'ever': 8063,
 'sort': 21842,
 'high': 11027,
 'school': 20429,
 'project': 18341,
 'rosanna': 19964,
 'arquette': 1625,
 'thinking': 23584,
 'stock': 22418,
 'bizarre': 2722,
 'supposed': 22886,
 'midwest': 14957,
 'town': 24035,
 'get': 9791,
 'involved': 12342,
 'lessons': 13581,
 'learned': 13474,
 'insights': 12106,
 'stilted': 22393,
 'quite': 18696,
 'ridiculous': 19713,
 'lots': 13986,
 'skin': 21434,
 'intrigues': 12287,
 'videotaped': 25153,
 'nonsensewhat': 16097,
 'bisexual': 2697,
 'relationship': 19236,
 'nowhere': 16211,
 'heterosexual': 10993,
 'encounters': 7717,
 'absurd': 476,
 'dance': 5878,
 'stereotyped': 22355,
 'pass': 17124,
 'million': 14997,
 'miles': 14976,
 'wasted': 25499,
 'could': 5368,
 'spent': 22001,
 'starving': 22273,
 'aids': 879,
 'africa': 781,
 'simply': 21316,
 'remade': 19281,
 'fails': 8433,
 'capture': 3742,
 'flavor': 8986,
 'terror': 23405,
 '1963': 134,
 'title': 23850,
 'liam': 13618,
 'neeson': 15852,
 'excellent': 8154,
 'always': 1106,
 'holds': 11199,
 'exception': 8163,
 'owen': 16885,
 'wilson': 25894,
 'feel': 8651,
 'character': 4108,
 'luke': 14100,
 'major': 14257,
 'fault': 8586,
 'version': 25103,
 'strayed': 22521,
 'shirley': 21081,
 'jackson': 12532,
 'attempts': 1843,
 'grandiose': 10156,
 'thrill': 23672,
 'earlier': 7353,
 'trade': 24058,
 'snazzier': 21652,
 'special': 21948,
 'effects': 7463,
 'enjoy': 7800,
 'friction': 9372,
 'older': 16445,
 'top': 23958,
 'horrible': 11329,
 'wasnt': 25493,
 'continuous': 5187,
 'minute': 15077,
 'fight': 8754,
 'chance': 4071,
 'development': 6467,
 'busy': 3518,
 'running': 20088,
 'sword': 23046,
 'emotional': 7657,
 'attachment': 1831,
 'except': 8161,
 'machine': 14173,
 'wanted': 25433,
 'destroy': 6411,
 'blatantly': 2780,
 'stolen': 22433,
 'lotr': 13985,
 'wars': 25477,
 'matrix': 14559,
 'examplesthe': 8144,
 'ghost': 9806,
 'final': 8847,
 'yoda': 26292,
 'obee': 16275,
 'vader': 24960,
 'spider': 22005,
 'beginning': 2428,
 'frodo': 9408,
 'attacked': 1833,
 'return': 19591,
 'kings': 13058,
 'elijah': 7561,
 'wood': 26033,
 'victim': 25137,
 'waitit': 25370,
 'hypnotizes': 11569,
 'stings': 22399,
 'wraps': 26146,
 'upuh': 24896,
 'helloand': 10893,
 'vs': 25328,
 'humans': 11469,
 'matrixor': 14561,
 'terminatorthere': 23391,
 'examples': 8143,
 'someone': 21780,
 'tell': 23331,
 'nazis': 15816,
 'juvenile': 12865,
 'line': 13747,
 'rushed': 20098,
 'conclusion': 4997,
 'childrens': 4270,
 'adult': 708,
 'either': 7508,
 'disappointment': 6668,
 'save': 20315,
 'remember': 19301,
 'filmit': 8801,
 'cinema': 4391,
 'dark': 5928,
 'places': 17671,
 'nervous': 15906,
 '7475': 357,
 'dad': 5830,
 'sister': 21364,
 'newbury': 15935,
 'berkshire': 2542,
 'england': 7782,
 'tigers': 23748,
 'snow': 21679,
 'appearance': 1477,
 'grizzly': 10277,
 'adams': 620,
 'actor': 599,
 'dan': 5876,
 'haggery': 10461,
 'think': 23582,
 'shot': 21139,
 'dies': 6552,
 'anyone': 1413,
 'knows': 13132,
 'dvd': 7309,
 'etc': 8008,
 'please': 17737,
 'knowthe': 13133,
 'turned': 24345,
 'fitness': 8929,
 'club': 4598,
 'shame': 20960,
 'nearest': 15824,
 '20': 191,
 'away': 2002,
 'hear': 10791,
 'others': 16700,
 'stinkers': 22402,
 'nominated': 16062,
 'golden': 9995,
 'globe': 9923,
 'theyve': 23560,
 'female': 8672,
 'renaissance': 19334,
 'painter': 16956,
 'mangled': 14321,
 'recognition': 19030,
 'complaint': 4905,
 'liberties': 13631,
 'facts': 8416,
 'perfectly': 17350,
 'fine': 8860,
 'accounts': 539,
 'artist': 1665,
 'dishwaterdull': 6746,
 'script': 20535,
 'suppose': 22885,
 'werent': 25690,
 'enough': 7816,
 'naked': 15729,
 'factual': 8419,
 'hurriedly': 11527,
 'capped': 3724,
 'summary': 22820,
 'artists': 1670,
 'saved': 20316,
 'couple': 5402,
 'hours': 11389,
 'favored': 8600,
 'brevity': 3236,
 'die': 6545,
 'sequels': 20810,
 'surprise': 22919,
 '1990s': 171,
 'glut': 9941,
 'cashed': 3870,
 'wrong': 26175,
 'guy': 10411,
 'concept': 4978,
 'cliffhanger': 4537,
 'mountain': 15434,
 'rescue': 19453,
 'sly': 21587,
 'stop': 22455,
 'stallones': 22204,
 'careercliffhanger': 3765,
 'nitpickers': 16019,
 'especially': 7979,
 'expert': 8279,
 'climbing': 4548,
 'basejumping': 2272,
 'aviation': 1970,
 'facial': 8403,
 'expressions': 8332,
 'skills': 21429,
 'full': 9456,
 'excuses': 8197,
 'dismiss': 6766,
 'overblown': 16800,
 'pile': 17583,
 'junk': 12847,
 'stallone': 22203,
 'outacted': 16715,
 'horse': 11355,
 'forget': 9187,
 'nonsense': 16094,
 'lovable': 14010,
 'undeniably': 24538,
 'romp': 19925,
 'plenty': 17751,
 'thrills': 23681,
 'unintentionally': 24683,
 ...}

Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

In [61]:
# bi gram
from sklearn.feature_extraction.text import CountVectorizer
cnvbi = CountVectorizer(ngram_range=(2,2)) 
bowbi = cnvbi.fit_transform(df['review'])
bowbi.toarray().shape

(1499, 147253)

In [62]:
cnvbi.vocabulary_

{'wonderful little': 143821,
 'little production': 74261,
 'production filming': 100722,
 'filming technique': 46791,
 'technique unassuming': 127551,
 'unassuming oldtimebbc': 135277,
 'oldtimebbc fashion': 90858,
 'fashion gives': 44116,
 'gives comforting': 53395,
 'comforting sometimes': 24287,
 'sometimes discomforting': 119588,
 'discomforting sense': 33317,
 'sense realism': 113949,
 'realism entire': 103797,
 'entire piece': 39046,
 'piece actors': 96480,
 'actors extremely': 2500,
 'extremely well': 42564,
 'well chosen': 141462,
 'chosen michael': 22027,
 'michael sheen': 81278,
 'sheen got': 115403,
 'got polari': 55222,
 'polari voices': 98374,
 'voices pat': 138758,
 'pat truly': 94344,
 'truly see': 133929,
 'see seamless': 112754,
 'seamless editing': 112063,
 'editing guided': 36586,
 'guided references': 56544,
 'references williams': 105052,
 'williams diary': 142841,
 'diary entries': 32092,
 'entries well': 39122,
 'well worth': 141770,
 'worth watching': 145043,
 'watching terrificly': 140533,
 'terrificly written': 128210,
 'written performed': 145835,
 'performed piece': 95563,
 'piece masterful': 96520,
 'masterful production': 79294,
 'production one': 100744,
 'one great': 91216,
 'great masters': 55806,
 'masters comedy': 79350,
 'comedy life': 24058,
 'life realism': 72377,
 'realism really': 103801,
 'really comes': 104054,
 'comes home': 24202,
 'home little': 60516,
 'little things': 74313,
 'things fantasy': 129312,
 'fantasy guard': 43909,
 'guard rather': 56415,
 'rather use': 103191,
 'use traditional': 136840,
 'traditional dream': 132930,
 'dream techniques': 35198,
 'techniques remains': 127561,
 'remains solid': 105736,
 'solid disappears': 119140,
 'disappears plays': 33136,
 'plays knowledge': 97513,
 'knowledge senses': 69352,
 'senses particularly': 113996,
 'particularly scenes': 94052,
 'scenes concerning': 110936,
 'concerning orton': 25262,
 'orton halliwell': 92437,
 'halliwell sets': 57175,
 'sets particularly': 114744,
 'particularly flat': 94024,
 'flat halliwells': 48337,
 'halliwells murals': 57176,
 'murals decorating': 86041,
 'decorating every': 30500,
 'every surface': 40804,
 'surface terribly': 125731,
 'terribly well': 128173,
 'well done': 141497,
 'thought wonderful': 130282,
 'wonderful way': 143860,
 'way spend': 140941,
 'spend time': 120764,
 'time hot': 131046,
 'hot summer': 61270,
 'summer weekend': 125215,
 'weekend sitting': 141308,
 'sitting air': 117870,
 'air conditioned': 4062,
 'conditioned theater': 25344,
 'theater watching': 128603,
 'watching lighthearted': 140460,
 'lighthearted comedy': 72592,
 'comedy plot': 24081,
 'plot simplistic': 97929,
 'simplistic dialogue': 117279,
 'dialogue witty': 32048,
 'witty characters': 143445,
 'characters likable': 20904,
 'likable even': 72651,
 'even well': 40365,
 'well bread': 141445,
 'bread suspected': 16113,
 'suspected serial': 126042,
 'serial killer': 114281,
 'killer may': 68534,
 'may disappointed': 79654,
 'disappointed realize': 33179,
 'realize match': 103932,
 'match point': 79378,
 'point risk': 98234,
 'risk addiction': 107820,
 'addiction thought': 3150,
 'thought proof': 130248,
 'proof woody': 101065,
 'woody allen': 144025,
 'allen still': 4474,
 'still fully': 122518,
 'fully control': 50605,
 'control style': 26115,
 'style many': 124492,
 'many us': 78832,
 'us grown': 136614,
 'grown lovethis': 56345,
 'lovethis id': 76355,
 'id laughed': 62463,
 'laughed one': 70602,
 'one woodys': 91662,
 'woodys comedies': 144032,
 'comedies years': 23986,
 'years dare': 146245,
 'dare say': 29241,
 'say decade': 110175,
 'decade ive': 30253,
 'ive never': 66223,
 'never impressed': 87895,
 'impressed scarlet': 63550,
 'scarlet johanson': 110533,
 'johanson managed': 66991,
 'managed tone': 78425,
 'tone sexy': 132098,
 'sexy image': 115081,
 'image jumped': 63108,
 'jumped right': 67563,
 'right average': 107556,
 'average spirited': 9845,
 'spirited young': 120892,
 'young womanthis': 146854,
 'womanthis may': 143647,
 'may crown': 79650,
 'crown jewel': 28396,
 'jewel career': 66726,
 'career wittier': 18695,
 'wittier devil': 143441,
 'devil wears': 31870,
 'wears prada': 141214,
 'prada interesting': 99389,
 'interesting superman': 65188,
 'superman great': 125375,
 'great comedy': 55685,
 'comedy go': 24039,
 'go see': 53834,
 'see friends': 112543,
 'basically theres': 11573,
 'theres family': 128853,
 'family little': 43519,
 'little boy': 74076,
 'boy jake': 15824,
 'jake thinks': 66377,
 'thinks theres': 129817,
 'theres zombie': 128923,
 'zombie closet': 147156,
 'closet parents': 23217,
 'parents fighting': 93614,
 'fighting timethis': 45350,
 'timethis movie': 131515,
 'movie slower': 84682,
 'slower soap': 118512,
 'soap opera': 118900,
 'opera suddenly': 91960,
 'suddenly jake': 124965,
 'jake decides': 66373,
 'decides become': 30419,
 'become rambo': 12137,
 'rambo kill': 102768,
 'kill zombieok': 68443,
 'zombieok first': 147183,
 'first youre': 48115,
 'youre going': 146921,
 'going make': 54240,
 'make film': 77494,
 'film must': 46197,
 'must decide': 86437,
 'decide thriller': 30372,
 'thriller drama': 130507,
 'drama drama': 34984,
 'drama movie': 35015,
 'movie watchable': 84888,
 'watchable parents': 140254,
 'parents divorcing': 93610,
 'divorcing arguing': 33854,
 'arguing like': 8092,
 'like real': 73233,
 'real life': 103683,
 'life jake': 72316,
 'jake closet': 66372,
 'closet totally': 23220,
 'totally ruins': 132534,
 'ruins film': 109040,
 'film expected': 45876,
 'expected see': 41971,
 'see boogeyman': 112428,
 'boogeyman similar': 15148,
 'similar movie': 117178,
 'movie instead': 84261,
 'instead watched': 64759,
 'watched drama': 140285,
 'drama meaningless': 35014,
 'meaningless thriller': 80100,
 'thriller spots3': 130531,
 'spots3 10': 121124,
 '10 well': 74,
 'well playing': 141659,
 'playing parents': 97424,
 'parents descent': 93608,
 'descent dialogs': 31244,
 'dialogs shots': 31972,
 'shots jake': 116111,
 'jake ignore': 66375,
 'petter matteis': 96045,
 'matteis love': 79480,
 'love time': 76150,
 'time money': 131105,
 'money visually': 82970,
 'visually stunning': 138639,
 'stunning film': 124278,
 'film watch': 46645,
 'watch mr': 140122,
 'mr mattei': 85460,
 'mattei offers': 79477,
 'offers us': 90289,
 'us vivid': 136730,
 'vivid portrait': 138668,
 'portrait human': 98830,
 'human relations': 61899,
 'relations movie': 105367,
 'movie seems': 84642,
 'seems telling': 113319,
 'telling us': 127844,
 'us money': 136653,
 'money power': 82949,
 'power success': 99294,
 'success people': 124823,
 'people different': 94827,
 'different situations': 32460,
 'situations encounter': 117942,
 'encounter variation': 37760,
 'variation arthur': 137427,
 'arthur schnitzlers': 8568,
 'schnitzlers play': 111227,
 'play theme': 97175,
 'theme director': 128668,
 'director transfers': 32990,
 'transfers action': 133123,
 'action present': 2266,
 'present time': 99775,
 'time new': 131123,
 'new york': 88202,
 'york different': 146624,
 'different characters': 32388,
 'characters meet': 20921,
 'meet connect': 80333,
 'connect one': 25528,
 'one connected': 91053,
 'connected one': 25539,
 'one way': 91644,
 'way another': 140662,
 'another next': 6868,
 'next person': 88307,
 'person one': 95814,
 'one seems': 91501,
 'seems know': 113254,
 'know previous': 69230,
 'previous point': 100048,
 'point contact': 98154,
 'contact stylishly': 25845,
 'stylishly film': 124539,
 'film sophisticated': 46481,
 'sophisticated luxurious': 119960,
 'luxurious look': 76630,
 'look taken': 75153,
 'taken see': 126724,
 'see people': 112698,
 'people live': 94921,
 'live world': 74410,
 'world live': 144658,
 'live habitatthe': 74379,
 'habitatthe thing': 56949,
 'thing one': 129209,
 'one gets': 91201,
 'gets souls': 52623,
 'souls picture': 120160,
 'picture different': 96386,
 'different stages': 32464,
 'stages loneliness': 121303,
 'loneliness one': 74808,
 'one inhabits': 91258,
 'inhabits big': 64316,
 'big city': 13710,
 'city exactly': 22419,
 'exactly best': 41262,
 'best place': 13189,
 'place human': 96825,
 'relations find': 105366,
 'find sincere': 47526,
 'sincere fulfillment': 117574,
 'fulfillment one': 50500,
 'one discerns': 91093,
 'discerns case': 33301,
 'case people': 19126,
 'people encounterthe': 94840,
 'encounterthe acting': 37773,
 'acting good': 2029,
 'good mr': 54725,
 'mr matteis': 85461,
 'matteis direction': 79479,
 'direction steve': 32796,
 'steve buscemi': 122337,
 'buscemi rosario': 17369,
 'rosario dawson': 108740,
 'dawson carol': 29594,
 'carol kane': 18833,
 'kane michael': 67710,
 'michael imperioli': 81255,
 'imperioli adrian': 63374,
 'adrian grenier': 3366,
 'grenier rest': 56083,
 'rest talented': 106720,
 'talented cast': 126980,
 'cast make': 19297,
 'make characters': 77448,
 'characters come': 20792,
 'come alivewe': 23791,
 'alivewe wish': 4434,
 'wish mr': 143114,
 'mattei good': 79475,
 'good luck': 54697,
 'luck await': 76485,
 'await anxiously': 9917,
 'anxiously next': 7108,
 'next work': 88330,
 'probably alltime': 100325,
 'alltime favorite': 4579,
 'favorite movie': 44438,
 'movie story': 84724,
 'story selflessness': 123386,
 'selflessness sacrifice': 113739,
 'sacrifice dedication': 109333,
 'dedication noble': 30515,
 'noble cause': 88713,
 'cause preachy': 19617,
 'preachy boring': 99432,
 'boring never': 15491,
 'never gets': 87871,
 'gets old': 52591,
 'old despite': 90680,
 'despite seen': 31533,
 'seen 15': 113340,
 '15 times': 219,
 'times last': 131413,
 'last 25': 70186,
 '25 years': 706,
 'years paul': 146306,
 'paul lukas': 94482,
 'lukas performance': 76552,
 'performance brings': 95313,
 'brings tears': 16489,
 'tears eyes': 127485,
 'eyes bette': 42632,
 'bette davis': 13334,
 'davis one': 29578,
 'one truly': 91609,
 'truly sympathetic': 133937,
 'sympathetic roles': 126357,
 'roles delight': 108379,
 'delight kids': 30803,
 'kids grandma': 68302,
 'grandma says': 55499,
 'says like': 110429,
 'like dressedup': 72861,
 'dressedup midgets': 35276,
 'midgets children': 81401,
 'children makes': 21769,
 'makes fun': 77772,
 'fun watch': 50721,
 'watch mothers': 140118,
 'mothers slow': 83477,
 'slow awakening': 118464,
 'awakening whats': 9931,
 'whats happening': 142106,
 'happening world': 57590,
 'world roof': 144696,
 'roof believable': 108616,
 'believable startling': 12696,
 'startling dozen': 121888,
 'dozen thumbs': 34841,
 'thumbs theyd': 130711,
 'theyd movie': 128946,
 'sure would': 125695,
 'would like': 145282,
 'like see': 73278,
 'see resurrection': 112741,
 'resurrection dated': 106838,
 'dated seahunt': 29411,
 'seahunt series': 112057,
 'series tech': 114395,
 'tech today': 127507,
 'today would': 131793,
 'would bring': 145137,
 'bring back': 16409,
 'back kid': 10502,
 'kid excitement': 68190,
 'excitement mei': 41645,
 'mei grew': 80453,
 'grew black': 56088,
 'black white': 14329,
 'white tv': 142379,
 'tv seahunt': 134585,
 'seahunt gunsmoke': 112056,
 'gunsmoke heros': 56643,
 'heros every': 59296,
 'every weekyou': 40820,
 'weekyou vote': 141326,
 'vote comeback': 138810,
 'comeback new': 23924,
 'new sea': 88164,
 'sea huntwe': 112034,
 'huntwe need': 62204,
 'need change': 87399,
 'change pace': 20203,
 'pace tv': 93174,
 'tv would': 134612,
 'would work': 145466,
 'work world': 144363,
 'world water': 144734,
 'water adventureoh': 140563,
 'adventureoh way': 3493,
 'way thank': 140958,
 'thank outlet': 128353,
 'outlet like': 92726,
 'like view': 73408,
 'view many': 138050,
 'many viewpoints': 78837,
 'viewpoints tv': 138250,
 'tv many': 134561,
 'many moviesso': 78747,
 'moviesso ole': 85357,
 'ole way': 90861,
 'way believe': 140679,
 'believe ive': 12752,
 'ive got': 66214,
 'got wanna': 55278,
 'wanna saywould': 139190,
 'saywould nice': 110463,
 'nice read': 88411,
 'read plus': 103463,
 'plus points': 98068,
 'points sea': 98336,
 'sea huntif': 112033,
 'huntif rhymes': 62192,
 'rhymes would': 107270,
 'would 10': 145083,
 '10 lines': 31,
 'lines would': 73822,
 'would let': 145280,
 'let submitor': 71907,
 'submitor leave': 124635,
 'leave doubt': 71275,
 'doubt quitif': 34724,
 'quitif must': 102469,
 'must go': 86466,
 'go lets': 53776,
 'show amazing': 116189,
 'amazing fresh': 5807,
 'fresh innovative': 50085,
 'innovative idea': 64439,
 'idea 70s': 62482,
 '70s first': 960,
 'first aired': 47856,
 'aired first': 4094,
 'first years': 48113,
 'years brilliant': 146232,
 'brilliant things': 16371,
 'things dropped': 129307,
 'dropped 1990': 35456,
 '1990 show': 505,
 'show really': 116372,
 'really funny': 104128,
 'funny anymore': 50792,
 'anymore continued': 7128,
 'continued decline': 25993,
 'decline complete': 30492,
 'complete waste': 24921,
 'waste time': 139931,
 'time todayits': 131251,
 'todayits truly': 131798,
 'truly disgraceful': 133884,
 'disgraceful far': 33453,
 'far show': 44009,
 'show fallen': 116264,
 'fallen writing': 43333,
 'writing painfully': 145761,
 'painfully bad': 93334,
 'bad performances': 10879,
 'performances almost': 95456,
 'almost bad': 4621,
 'bad mildly': 10847,
 'mildly entertaining': 81591,
 'entertaining respite': 38940,
 'respite guesthosts': 106615,
 'guesthosts show': 56519,
 'show probably': 116362,
 'probably wouldnt': 100443,
 'wouldnt still': 145509,
 'still air': 122440,
 'air find': 4064,
 'find hard': 47433,
 'hard believe': 57734,
 'believe creator': 12725,
 'creator handselected': 27841,
 'handselected original': 57414,
 'original cast': 92263,
 'cast also': 19222,
 'also chose': 5033,
 'chose band': 22005,
 'band hacks': 11163,
 'hacks followed': 56967,
 'followed one': 48850,
 'one recognize': 91464,
 'recognize brilliance': 104729,
 'brilliance see': 16319,
 'see fit': 112534,
 'fit replace': 48184,
 'replace mediocrity': 106224,
 'mediocrity felt': 80294,
 'felt must': 45028,
 'must give': 86465,
 'give stars': 53256,
 'stars respect': 121722,
 'respect original': 106574,
 'cast made': 19296,
 'made show': 77029,
 'show huge': 116301,
 'huge success': 61804,
 'success show': 124829,
 'show awful': 116197,
 'awful cant': 10185,
 'cant believe': 18288,
 'believe still': 12808,
 'encouraged positive': 37784,
 'positive comments': 98992,
 'comments film': 24482,
 'film looking': 46126,
 'looking forward': 75256,
 'forward watching': 49519,
 'watching film': 140427,
 'film bad': 45585,
 'bad mistake': 10848,
 'mistake ive': 82433,
 'ive seen': 66234,
 'seen 950': 113344,
 '950 films': 1116,
 'films truly': 47139,
 'truly one': 133920,
 'one worst': 91665,
 'worst awful': 144882,
 'awful almost': 10178,
 'almost every': 4646,
 'every way': 40817,
 'way editing': 140737,
 'editing pacing': 36592,
 'pacing storyline': 93207,
 'storyline acting': 123507,
 'acting soundtrack': 2145,
 'soundtrack films': 120269,
 'films song': 47110,
 'song lame': 119784,
 'lame country': 69926,
 'country tune': 27138,
 'tune played': 134235,
 'played less': 97265,
 'less four': 71748,
 'four times': 49710,
 'times film': 131390,
 'film looks': 46127,
 'looks cheap': 75331,
 'cheap nasty': 21353,
 'nasty boring': 87060,
 'boring extreme': 15467,
 'extreme rarely': 42497,
 'rarely happy': 102976,
 'happy see': 57705,
 'see end': 112496,
 'end credits': 37826,
 'credits film': 27953,
 'film thing': 46558,
 'thing prevents': 129219,
 'prevents giving': 100024,
 'giving 1score': 53447,
 '1score harvey': 553,
 'harvey keitel': 58035,
 'keitel far': 67965,
 'far best': 43937,
 'best performance': 13184,
 'performance least': 95385,
 'least seems': 71217,
 'seems making': 113266,
 'making bit': 77918,
 'bit effort': 14075,
 'effort one': 36901,
 'one keitel': 91279,
 'keitel obsessives': 67966,
 'like original': 73185,
 'original gut': 92299,
 'gut wrenching': 56671,
 'wrenching laughter': 145593,
 'laughter like': 70701,
 'like movie': 73148,
 'movie young': 84942,
 'young old': 146811,
 'old love': 90737,
 'love movie': 76082,
 'movie hell': 84211,
 'hell even': 58854,
 'even mom': 40163,
 'mom liked': 82707,
 'liked itgreat': 73477,
 'itgreat camp': 66109,
 'phil alien': 96104,
 'alien one': 4346,
 'one quirky': 91449,
 'quirky films': 102307,
 'films humour': 46995,
 'humour based': 62096,
 'based around': 11427,
 'around oddness': 8344,
 'oddness everything': 90178,
 'everything rather': 41060,
 'rather actual': 103051,
 'actual punchlinesat': 2782,
 'punchlinesat first': 101630,
 'first odd': 48000,
 'odd pretty': 90152,
 'pretty funny': 99943,
 'funny movie': 50891,
 'movie progressed': 84544,
 'progressed didnt': 100909,
 'didnt find': 32162,
 'find jokes': 47448,
 'jokes oddness': 67210,
 'oddness funny': 90179,
 'funny anymoreits': 50793,
 'anymoreits low': 7141,
 'low budget': 76372,
 'budget film': 16970,
 'film thats': 46549,
 'thats never': 128493,
 'never problem': 87954,
 'problem pretty': 100488,
 'pretty interesting': 99957,
 'interesting characters': 65104,
 'characters eventually': 20832,
 'eventually lost': 40472,
 'lost interesti': 75577,
 'interesti imagine': 65086,
 'imagine film': 63185,
 'film would': 46682,
 'would appeal': 145105,
 'appeal stoner': 7652,
 'stoner currently': 122825,
 'currently partakingfor': 28731,
 'partakingfor something': 93928,
 'something similar': 119518,
 'similar better': 117161,
 'better try': 13549,
 'try brother': 134027,
 'brother another': 16657,
 'another planet': 6882,
 'saw movie': 110075,
 'movie 12': 83706,
 '12 came': 152,
 'came recall': 17930,
 'recall scariest': 104603,
 'scariest scene': 110531,
 'scene big': 110630,
 'big bird': 13697,
 'bird eating': 14001,
 'eating men': 36449,
 'men dangling': 80655,
 'dangling helplessly': 29189,
 'helplessly parachutes': 59074,
 'parachutes right': 93534,
 'right air': 107545,
 'air horror': 4068,
 'horror horroras': 61084,
 'horroras young': 61132,
 'young kid': 146790,
 'kid going': 68194,
 'going cheesy': 54165,
 'cheesy films': 21494,
 'films saturday': 47088,
 'saturday afternoons': 109895,
 'afternoons still': 3681,
 'still tired': 122638,
 'tired formula': 131591,
 'formula monster': 49415,
 'monster type': 83060,
 'type movies': 135049,
 'movies usually': 85323,
 'usually included': 137146,
 'included hero': 63760,
 'hero beautiful': 59209,
 'beautiful woman': 11981,
 'woman might': 143565,
 'might daughter': 81457,
 'daughter professor': 29459,
 'professor happy': 100833,
 'happy resolution': 57703,
 'resolution monster': 106514,
 'monster died': 83046,
 'died end': 32281,
 'end didnt': 37829,
 'didnt care': 32151,
 'care much': 18631,
 'much romantic': 85853,
 'romantic angle': 108536,
 'angle 12': 6416,
 '12 year': 162,
 'year old': 146168,
 'old predictable': 90759,
 'predictable plots': 99536,
 'plots love': 98012,
 'love unintentional': 76162,
 'unintentional humorbut': 135902,
 'humorbut year': 62077,
 'year later': 146159,
 'later saw': 70421,
 'saw psycho': 110089,
 'psycho came': 101413,
 'came loved': 17917,
 'loved star': 76247,
 'star janet': 121541,
 'janet leigh': 66460,
 'leigh bumped': 71605,
 'bumped early': 17189,
 'early film': 36185,
 'film sat': 46406,
 'sat took': 109814,
 'took notice': 132216,
 'notice point': 89388,
 'point since': 98242,
 'since screenwriters': 117544,
 'screenwriters making': 111797,
 'making story': 78020,
 'story make': 123286,
 'make scary': 77606,
 'scary possible': 110565,
 'possible wellworn': 99099,
 'wellworn formula': 141848,
 'formula rules': 49418,
 'im big': 62977,
 'big fan': 13733,
 'fan bolls': 43648,
 'bolls work': 15032,
 'work many': 144274,
 'many enjoyed': 78667,
 'enjoyed movie': 38594,
 'movie postal': 84525,
 'postal maybe': 99149,
 'maybe im': 79829,
 'im one': 63045,
 'one boll': 90996,
 'boll apparently': 15019,
 'apparently bought': 7584,
 'bought rights': 15696,
 'rights use': 107706,
 'use far': 136780,
 'far cry': 43949,
 'cry long': 28490,
 'long ago': 74828,
 'ago even': 3874,
 'even game': 40043,
 'game even': 51247,
 'even finsished': 40028,
 'finsished people': 47777,
 'people enjoyed': 94842,
 'enjoyed killing': 38586,

In [67]:
# tri gram
from sklearn.feature_extraction.text import CountVectorizer
cnvtri = CountVectorizer(ngram_range=(3,3)) 
bowtri = cnvtri.fit_transform(df['review'])
bowtri.toarray().shape

(1499, 169343)

In [68]:
cnvtri.vocabulary_

{'wonderful little production': 165014,
 'little production filming': 84499,
 'production filming technique': 116211,
 'filming technique unassuming': 53140,
 'technique unassuming oldtimebbc': 146227,
 'unassuming oldtimebbc fashion': 155204,
 'oldtimebbc fashion gives': 104773,
 'fashion gives comforting': 49389,
 'gives comforting sometimes': 60653,
 'comforting sometimes discomforting': 27160,
 'sometimes discomforting sense': 137438,
 'discomforting sense realism': 36944,
 'sense realism entire': 131216,
 'realism entire piece': 119600,
 'entire piece actors': 43506,
 'piece actors extremely': 111412,
 'actors extremely well': 2888,
 'extremely well chosen': 47669,
 'well chosen michael': 162230,
 'chosen michael sheen': 24703,
 'michael sheen got': 92770,
 'sheen got polari': 132826,
 'got polari voices': 63011,
 'polari voices pat': 113596,
 'voices pat truly': 158905,
 'pat truly see': 109047,
 'truly see seamless': 153594,
 'see seamless editing': 129767,
 'seamless editing guided': 128863,
 'editing guided references': 40764,
 'guided references williams': 64546,
 'references williams diary': 121175,
 'williams diary entries': 163939,
 'diary entries well': 35526,
 'entries well worth': 43590,
 'well worth watching': 162675,
 'worth watching terrificly': 166427,
 'watching terrificly written': 161172,
 'terrificly written performed': 146971,
 'written performed piece': 167551,
 'performed piece masterful': 110450,
 'piece masterful production': 111465,
 'masterful production one': 90617,
 'production one great': 116233,
 'one great masters': 105354,
 'great masters comedy': 63696,
 'masters comedy life': 90673,
 'comedy life realism': 26879,
 'life realism really': 82164,
 'realism really comes': 119604,
 'really comes home': 119898,
 'comes home little': 27063,
 'home little things': 68882,
 'little things fantasy': 84552,
 'things fantasy guard': 148238,
 'fantasy guard rather': 49144,
 'guard rather use': 64403,
 'rather use traditional': 118857,
 'use traditional dream': 156870,
 'traditional dream techniques': 152528,
 'dream techniques remains': 39272,
 'techniques remains solid': 146237,
 'remains solid disappears': 121871,
 'solid disappears plays': 136895,
 'disappears plays knowledge': 36756,
 'plays knowledge senses': 112528,
 'knowledge senses particularly': 78766,
 'senses particularly scenes': 131266,
 'particularly scenes concerning': 108745,
 'scenes concerning orton': 127604,
 'concerning orton halliwell': 28205,
 'orton halliwell sets': 107024,
 'halliwell sets particularly': 65245,
 'sets particularly flat': 132093,
 'particularly flat halliwells': 108715,
 'flat halliwells murals': 55038,
 'halliwells murals decorating': 65246,
 'murals decorating every': 99273,
 'decorating every surface': 33871,
 'every surface terribly': 45709,
 'surface terribly well': 144259,
 'terribly well done': 146933,
 'thought wonderful way': 149476,
 'wonderful way spend': 165066,
 'way spend time': 161674,
 'spend time hot': 138775,
 'time hot summer': 150385,
 'hot summer weekend': 69751,
 'summer weekend sitting': 143677,
 'weekend sitting air': 162059,
 'sitting air conditioned': 135527,
 'air conditioned theater': 4588,
 'conditioned theater watching': 28287,
 'theater watching lighthearted': 147410,
 'watching lighthearted comedy': 161059,
 'lighthearted comedy plot': 82397,
 'comedy plot simplistic': 26905,
 'plot simplistic dialogue': 113078,
 'simplistic dialogue witty': 134861,
 'dialogue witty characters': 35479,
 'witty characters likable': 164598,
 'characters likable even': 23480,
 'likable even well': 82457,
 'even well bread': 45052,
 'well bread suspected': 162209,
 'bread suspected serial': 18120,
 'suspected serial killer': 144589,
 'serial killer may': 131568,
 'killer may disappointed': 77806,
 'may disappointed realize': 91008,
 'disappointed realize match': 36801,
 'realize match point': 119743,
 'match point risk': 90704,
 'point risk addiction': 113431,
 'risk addiction thought': 124109,
 'addiction thought proof': 3643,
 'thought proof woody': 149427,
 'proof woody allen': 116568,
 'woody allen still': 165256,
 'allen still fully': 5028,
 'still fully control': 140656,
 'fully control style': 57414,
 'control style many': 29075,
 'style many us': 142928,
 'many us grown': 90109,
 'us grown lovethis': 156624,
 'grown lovethis id': 64333,
 'lovethis id laughed': 86995,
 'id laughed one': 71082,
 'laughed one woodys': 80154,
 'one woodys comedies': 106126,
 'woodys comedies years': 165264,
 'comedies years dare': 26792,
 'years dare say': 168055,
 'dare say decade': 32495,
 'say decade ive': 126721,
 'decade ive never': 33593,
 'ive never impressed': 75189,
 'never impressed scarlet': 101361,
 'impressed scarlet johanson': 72342,
 'scarlet johanson managed': 127154,
 'johanson managed tone': 76113,
 'managed tone sexy': 89579,
 'tone sexy image': 151622,
 'sexy image jumped': 132483,
 'image jumped right': 71882,
 'jumped right average': 76750,
 'right average spirited': 123824,
 'average spirited young': 10947,
 'spirited young womanthis': 138922,
 'young womanthis may': 168862,
 'womanthis may crown': 164817,
 'may crown jewel': 91004,
 'crown jewel career': 31609,
 'jewel career wittier': 75827,
 'career wittier devil': 21030,
 'wittier devil wears': 164594,
 'devil wears prada': 35293,
 'wears prada interesting': 161962,
 'prada interesting superman': 114679,
 'interesting superman great': 74056,
 'superman great comedy': 143846,
 'great comedy go': 63520,
 'comedy go see': 26857,
 'go see friends': 61195,
 'basically theres family': 13014,
 'theres family little': 147682,
 'family little boy': 48711,
 'little boy jake': 84254,
 'boy jake thinks': 17815,
 'jake thinks theres': 75427,
 'thinks theres zombie': 148916,
 'theres zombie closet': 147781,
 'zombie closet parents': 169237,
 'closet parents fighting': 25961,
 'parents fighting timethis': 108248,
 'fighting timethis movie': 50852,
 'timethis movie slower': 150977,
 'movie slower soap': 97326,
 'slower soap opera': 136222,
 'soap opera suddenly': 136646,
 'opera suddenly jake': 106489,
 'suddenly jake decides': 143422,
 'jake decides become': 75424,
 'decides become rambo': 33784,
 'become rambo kill': 13617,
 'rambo kill zombieok': 118407,
 'kill zombieok first': 77710,
 'zombieok first youre': 169273,
 'first youre going': 54797,
 'youre going make': 168941,
 'going make film': 61672,
 'make film must': 88406,
 'film must decide': 52217,
 'must decide thriller': 99713,
 'decide thriller drama': 33723,
 'thriller drama drama': 149751,
 'drama drama movie': 39049,
 'drama movie watchable': 39081,
 'movie watchable parents': 97701,
 'watchable parents divorcing': 160793,
 'parents divorcing arguing': 108243,
 'divorcing arguing like': 37483,
 'arguing like real': 9113,
 'like real life': 83242,
 'real life jake': 119436,
 'life jake closet': 82084,
 'jake closet totally': 75423,
 'closet totally ruins': 25964,
 'totally ruins film': 152096,
 'ruins film expected': 125439,
 'film expected see': 51605,
 'expected see boogeyman': 47052,
 'see boogeyman similar': 129277,
 'boogeyman similar movie': 17078,
 'similar movie instead': 134752,
 'movie instead watched': 96479,
 'instead watched drama': 73580,
 'watched drama meaningless': 160825,
 'drama meaningless thriller': 39080,
 'meaningless thriller spots3': 91518,
 'thriller spots3 10': 149775,
 'spots3 10 well': 139160,
 '10 well playing': 94,
 'well playing parents': 162512,
 'playing parents descent': 112435,
 'parents descent dialogs': 108241,
 'descent dialogs shots': 34641,
 'dialogs shots jake': 35402,
 'shots jake ignore': 133594,
 'petter matteis love': 110963,
 'matteis love time': 90815,
 'love time money': 86765,
 'time money visually': 150471,
 'money visually stunning': 94694,
 'visually stunning film': 158776,
 'stunning film watch': 142694,
 'film watch mr': 52932,
 'watch mr mattei': 160629,
 'mr mattei offers': 98504,
 'mattei offers us': 90812,
 'offers us vivid': 104119,
 'us vivid portrait': 156750,
 'vivid portrait human': 158806,
 'portrait human relations': 114098,
 'human relations movie': 70492,
 'relations movie seems': 121496,
 'movie seems telling': 97254,
 'seems telling us': 130458,
 'telling us money': 146563,
 'us money power': 156665,
 'money power success': 94668,
 'power success people': 114578,
 'success people different': 143278,
 'people different situations': 109569,
 'different situations encounter': 36026,
 'situations encounter variation': 135603,
 'encounter variation arthur': 42015,
 'variation arthur schnitzlers': 157496,
 'arthur schnitzlers play': 9620,
 'schnitzlers play theme': 127938,
 'play theme director': 112163,
 'theme director transfers': 147475,
 'director transfers action': 36598,
 'transfers action present': 152728,
 'action present time': 2596,
 'present time new': 115076,
 'time new york': 150496,
 'new york different': 101827,
 'york different characters': 168522,
 'different characters meet': 35949,
 'characters meet connect': 23500,
 'meet connect one': 91758,
 'connect one connected': 28477,
 'one connected one': 105088,
 'connected one way': 28488,
 'one way another': 106096,
 'way another next': 161311,
 'another next person': 7762,
 'next person one': 101965,
 'person one seems': 110711,
 'one seems know': 105848,
 'seems know previous': 130366,
 'know previous point': 78614,
 'previous point contact': 115460,
 'point contact stylishly': 113327,
 'contact stylishly film': 28800,
 'stylishly film sophisticated': 142975,
 'film sophisticated luxurious': 52674,
 'sophisticated luxurious look': 137836,
 'luxurious look taken': 87303,
 'look taken see': 85532,
 'taken see people': 145327,
 'see people live': 129698,
 'people live world': 109706,
 'live world live': 84667,
 'world live habitatthe': 165946,
 'live habitatthe thing': 84633,
 'habitatthe thing one': 64987,
 'thing one gets': 148114,
 'one gets souls': 105329,
 'gets souls picture': 59778,
 'souls picture different': 138059,
 'picture different stages': 111315,
 'different stages loneliness': 36031,
 'stages loneliness one': 139343,
 'loneliness one inhabits': 85083,
 'one inhabits big': 105430,
 'inhabits big city': 73125,
 'big city exactly': 15458,
 'city exactly best': 25124,
 'exactly best place': 46274,
 'best place human': 14836,
 'place human relations': 111783,
 'human relations find': 70491,
 'relations find sincere': 121494,
 'find sincere fulfillment': 54006,
 'sincere fulfillment one': 135200,
 'fulfillment one discerns': 57302,
 'one discerns case': 105149,
 'discerns case people': 36928,
 'case people encounterthe': 21480,
 'people encounterthe acting': 109587,
 'encounterthe acting good': 42028,
 'acting good mr': 2277,
 'good mr matteis': 62370,
 'mr matteis direction': 98505,
 'matteis direction steve': 90814,
 'direction steve buscemi': 36380,
 'steve buscemi rosario': 140451,
 'buscemi rosario dawson': 19468,
 'rosario dawson carol': 125133,
 'dawson carol kane': 32881,
 'carol kane michael': 21169,
 'kane michael imperioli': 76908,
 'michael imperioli adrian': 92744,
 'imperioli adrian grenier': 72156,
 'adrian grenier rest': 3860,
 'grenier rest talented': 64055,
 'rest talented cast': 122940,
 'talented cast make': 145631,
 'cast make characters': 21682,
 'make characters come': 88347,
 'characters come alivewe': 23339,
 'come alivewe wish': 26566,
 'alivewe wish mr': 4987,
 'wish mr mattei': 164228,
 'mr mattei good': 98503,
 'mattei good luck': 90810,
 'good luck await': 62304,
 'luck await anxiously': 87153,
 'await anxiously next': 11019,
 'anxiously next work': 8021,
 'probably alltime favorite': 115750,
 'alltime favorite movie': 5136,
 'favorite movie story': 49751,
 'movie story selflessness': 97414,
 'story selflessness sacrifice': 141717,
 'selflessness sacrifice dedication': 130993,
 'sacrifice dedication noble': 125753,
 'dedication noble cause': 33886,
 'noble cause preachy': 102417,
 'cause preachy boring': 22027,
 'preachy boring never': 114722,
 'boring never gets': 17447,
 'never gets old': 101323,
 'gets old despite': 59740,
 'old despite seen': 104545,
 'despite seen 15': 34941,
 'seen 15 times': 130480,
 '15 times last': 261,
 'times last 25': 150860,
 'last 25 years': 79644,
 '25 years paul': 792,
 'years paul lukas': 168156,
 'paul lukas performance': 109192,
 'lukas performance brings': 87220,
 'performance brings tears': 110174,
 'brings tears eyes': 18517,
 'tears eyes bette': 146156,
 'eyes bette davis': 47743,
 'bette davis one': 15008,
 'davis one truly': 32863,
 'one truly sympathetic': 106034,
 'truly sympathetic roles': 153602,
 'sympathetic roles delight': 144923,
 'roles delight kids': 124744,
 'delight kids grandma': 34189,
 'kids grandma says': 77549,
 'grandma says like': 63306,
 'says like dressedup': 127042,
 'like dressedup midgets': 82707,
 'dressedup midgets children': 39351,
 'midgets children makes': 92915,
 'children makes fun': 24437,
 'makes fun watch': 88815,
 'fun watch mothers': 57544,
 'watch mothers slow': 160587,
 'mothers slow awakening': 95241,
 'slow awakening whats': 136158,
 'awakening whats happening': 11033,
 'whats happening world': 163060,
 'happening world roof': 65677,
 'world roof believable': 165986,
 'roof believable startling': 125008,
 'believable startling dozen': 14223,
 'startling dozen thumbs': 139983,
 'dozen thumbs theyd': 38896,
 'thumbs theyd movie': 149992,
 'sure would like': 144220,
 'would like see': 166782,
 'like see resurrection': 83321,
 'see resurrection dated': 129754,
 'resurrection dated seahunt': 123059,
 'dated seahunt series': 32691,
 'seahunt series tech': 128857,
 'series tech today': 131711,
 'tech today would': 146180,
 'today would bring': 151273,
 'would bring back': 166557,
 'bring back kid': 18432,
 'back kid excitement': 11669,
 'kid excitement mei': 77430,
 'excitement mei grew': 46703,
 'mei grew black': 91881,
 'grew black white': 64060,
 'black white tv': 16201,
 'white tv seahunt': 163355,
 'tv seahunt gunsmoke': 154339,
 'seahunt gunsmoke heros': 128856,
 'gunsmoke heros every': 64647,
 'heros every weekyou': 67547,
 'every weekyou vote': 45749,
 'weekyou vote comeback': 162078,
 'vote comeback new': 158957,
 'comeback new sea': 26725,
 'new sea huntwe': 101753,
 'sea huntwe need': 128833,
 'huntwe need change': 70806,
 'need change pace': 100781,
 'change pace tv': 22649,
 'pace tv would': 107793,
 'tv would work': 154392,
 'would work world': 167140,
 'work world water': 165629,
 'world water adventureoh': 166036,
 'water adventureoh way': 161206,
 'adventureoh way thank': 3996,
 'way thank outlet': 161697,
 'thank outlet like': 147129,
 'outlet like view': 107332,
 'like view many': 83489,
 'view many viewpoints': 158159,
 'many viewpoints tv': 90116,
 'viewpoints tv many': 158368,
 'tv many moviesso': 154305,
 'many moviesso ole': 89945,
 'moviesso ole way': 98388,
 'ole way believe': 104776,
 'way believe ive': 161339,
 'believe ive got': 14284,
 'ive got wanna': 75176,
 'got wanna saywould': 63075,
 'wanna saywould nice': 159374,
 'saywould nice read': 127082,
 'nice read plus': 102088,
 'read plus points': 119171,
 'plus points sea': 113238,
 'points sea huntif': 113554,
 'sea huntif rhymes': 128832,
 'huntif rhymes would': 70792,
 'rhymes would 10': 123514,
 'would 10 lines': 166470,
 '10 lines would': 39,
 'lines would let': 83967,
 'would let submitor': 166762,
 'let submitor leave': 81612,
 'submitor leave doubt': 143085,
 'leave doubt quitif': 80927,
 'doubt quitif must': 38778,
 'quitif must go': 118095,
 'must go lets': 99749,
 'show amazing fresh': 133674,
 'amazing fresh innovative': 6597,
 'fresh innovative idea': 56862,
 'innovative idea 70s': 73249,
 'idea 70s first': 71124,
 '70s first aired': 1075,
 'first aired first': 54376,
 'aired first years': 4621,
 'first years brilliant': 54795,
 'years brilliant things': 168040,
 'brilliant things dropped': 18391,
 'things dropped 1990': 148232,
 'dropped 1990 show': 39541,
 '1990 show really': 558,
 'show really funny': 133886,
 'really funny anymore': 119998,
 'funny anymore continued': 57625,
 'anymore continued decline': 8042,
 'continued decline complete': 28951,
 'decline complete waste': 33863,
 'complete waste time': 27835,
 'waste time todayits': 160339,
 'time todayits truly': 150666,
 'todayits truly disgraceful': 151278,
 'truly disgraceful far': 153545,
 'disgraceful far show': 37079,
 'far show fallen': 49278,
 'show fallen writing': 133758,
 'fallen writing painfully': 48496,
 'writing painfully bad': 167470,
 'painfully bad performances': 107956,
 'bad performances almost': 12231,
 'performances almost bad': 110328,
 'almost bad mildly': 5182,
 'bad mildly entertaining': 12153,
 'mildly entertaining respite': 93159,
 'entertaining respite guesthosts': 43361,
 'respite guesthosts show': 122802,
 'guesthosts show probably': 64521,
 'show probably wouldnt': 133876,
 'probably wouldnt still': 115913,
 'wouldnt still air': 167191,
 'still air find': 140564,
 'air find hard': 4590,
 'find hard believe': 53892,
 'hard believe creator': 65837,
 'believe creator handselected': 14254,
 'creator handselected original': 31037,
 'handselected original cast': 65488,
 'original cast also': 106805,
 'cast also chose': 21584,
 'also chose band': 5664,
 'chose band hacks': 24681,
 'band hacks followed': 12563,
 'hacks followed one': 65005,
 'followed one recognize': 55564,
 'one recognize brilliance': 105791,
 'recognize brilliance see': 120812,
 'brilliance see fit': 18338,
 'see fit replace': 129443,
 'fit replace mediocrity': 54866,
 'replace mediocrity felt': 122404,
 'mediocrity felt must': 91719,
 'felt must give': 50497,
 'must give stars': 99747,
 'give stars respect': 60493,
 'stars respect original': 139799,
 'respect original cast': 122760,
 'original cast made': 106806,
 'cast made show': 21681,
 'made show huge': 87803,
 'show huge success': 133798,
 'huge success show': 70365,
 'success show awful': 143284,
 'show awful cant': 133684,
 'awful cant believe': 11305,
 'cant believe still': 20473,
 'believe still air': 14351,
 'encouraged positive comments': 42039,
 'positive comments film': 114262,
 'comments film looking': 27377,
 'film looking forward': 52038,
 'looking forward watching': 85660,
 'forward watching film': 56252,
 'watching film bad': 161010,
 'film bad mistake': 51157,
 'bad mistake ive': 12154,
 'mistake ive seen': 94094,
 'ive seen 950': 75209,
 'seen 950 films': 130484,
 '950 films truly': 1247,
 'films truly one': 53555,
 'truly one worst': 153583,
 'one worst awful': 106132,
 'worst awful almost': 166192,
 'awful almost every': 11298,
 'almost every way': 5217,
 'every way editing': 45739,
 'way editing pacing': 161409,
 'editing pacing storyline': 40770,
 'pacing storyline acting': 107827,
 'storyline acting soundtrack': 141888,
 'acting soundtrack films': 2429,
 'soundtrack films song': 138186,
 'films song lame': 53518,
 'song lame country': 137647,
 'lame country tune': 79376,
 'country tune played': 30287,
 'tune played less': 153963,
 'played less four': 112263,
 'less four times': 81429,
 'four times film': 56466,
 'times film looks': 150831,
 'film looks cheap': 52041,
 'looks cheap nasty': 85742,
 'cheap nasty boring': 23999,
 'nasty boring extreme': 100417,
 'boring extreme rarely': 17418,
 'extreme rarely happy': 47593,
 'rarely happy see': 118625,
 'happy see end': 65802,
 'see end credits': 129364,
 'end credits film': 42084,
 'credits film thing': 31149,
 'film thing prevents': 52797,
 'thing prevents giving': 148126,
 'prevents giving 1score': 115432,
 'giving 1score harvey': 60720,
 '1score harvey keitel': 610,
 'harvey keitel far': 66191,
 'keitel far best': 77183,
 'far best performance': 49177,
 'best performance least': 14822,
 'performance least seems': 110251,
 'least seems making': 80855,
 'seems making bit': 130403,
 'making bit effort': 89017,
 'bit effort one': 15901,
 'effort one keitel': 41096,
 'one keitel obsessives': 105460,
 'like original gut': 83182,
 'original gut wrenching': 106849,

Apply tf-idf and find out the idf scores of words, also find out the vocabulary

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfi = TfidfVectorizer(ngram_range=(1,3))
tfibow = tfi.fit_transform(df['review']).toarray()

print(tfibow.shape)

(1499, 343029)

In [77]:
tfibow

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [78]:
tfi.vocabulary_

{'wonderful': 334764,
 'little': 172071,
 'production': 235177,
 'filming': 108694,
 'technique': 297051,
 'unassuming': 314967,
 'oldtimebbc': 212088,
 'fashion': 102038,
 'gives': 123893,
 'comforting': 56247,
 'sometimes': 278796,
 'discomforting': 76954,
 'sense': 265792,
 'realism': 242340,
 'entire': 90322,
 'piece': 225456,
 'actors': 5858,
 'extremely': 98464,
 'well': 329218,
 'chosen': 51059,
 'michael': 188869,
 'sheen': 269243,
 'got': 128084,
 'polari': 229812,
 'voices': 322944,
 'pat': 220531,
 'truly': 311665,
 'see': 262247,
 'seamless': 261500,
 'editing': 84765,
 'guided': 131445,
 'references': 245334,
 'williams': 332640,
 'diary': 74135,
 'entries': 90585,
 'worth': 337395,
 'watching': 326822,
 'terrificly': 298581,
 'written': 339469,
 'performed': 223373,
 'masterful': 184420,
 'one': 212245,
 'great': 129283,
 'masters': 184548,
 'comedy': 55562,
 'life': 167775,
 'really': 242756,
 'comes': 55934,
 'home': 140533,
 'things': 301037,
 'fantasy': 101547,
 'guard': 131128,
 'rather': 240623,
 'use': 318452,
 'traditional': 309512,
 'dream': 81556,
 'techniques': 297081,
 'remains': 246843,
 'solid': 277774,
 'disappears': 76545,
 'plays': 227667,
 'knowledge': 161216,
 'senses': 266023,
 'particularly': 219803,
 'scenes': 258852,
 'concerning': 58445,
 'orton': 216133,
 'halliwell': 132927,
 'sets': 267639,
 'flat': 112329,
 'halliwells': 132930,
 'murals': 200922,
 'decorating': 70496,
 'every': 94294,
 'surface': 292867,
 'terribly': 298489,
 'done': 79281,
 'wonderful little': 334858,
 'little production': 172579,
 'production filming': 235230,
 'filming technique': 108731,
 'technique unassuming': 297077,
 'unassuming oldtimebbc': 314968,
 'oldtimebbc fashion': 212089,
 'fashion gives': 102051,
 'gives comforting': 123926,
 'comforting sometimes': 56250,
 'sometimes discomforting': 278817,
 'discomforting sense': 76957,
 'sense realism': 265935,
 'realism entire': 242349,
 'entire piece': 90412,
 'piece actors': 225459,
 'actors extremely': 5992,
 'extremely well': 98596,
 'well chosen': 329334,
 'chosen michael': 51066,
 'michael sheen': 188956,
 'sheen got': 269246,
 'got polari': 128318,
 'polari voices': 229813,
 'voices pat': 322955,
 'pat truly': 220543,
 'truly see': 311813,
 'see seamless': 263154,
 'seamless editing': 261501,
 'editing guided': 84784,
 'guided references': 131446,
 'references williams': 245357,
 'williams diary': 332656,
 'diary entries': 74136,
 'entries well': 90588,
 'well worth': 330073,
 'worth watching': 337578,
 'watching terrificly': 327223,
 'terrificly written': 298582,
 'written performed': 339559,
 'performed piece': 223378,
 'piece masterful': 225552,
 'masterful production': 184425,
 'production one': 235274,
 'one great': 213062,
 'great masters': 129705,
 'masters comedy': 184549,
 'comedy life': 55720,
 'life realism': 168196,
 'realism really': 242357,
 'really comes': 242916,
 'comes home': 56061,
 'home little': 140632,
 'little things': 172684,
 'things fantasy': 301125,
 'fantasy guard': 101562,
 'guard rather': 131152,
 'rather use': 240928,
 'use traditional': 318629,
 'traditional dream': 309521,
 'dream techniques': 81596,
 'techniques remains': 297098,
 'remains solid': 246894,
 'solid disappears': 277791,
 'disappears plays': 76554,
 'plays knowledge': 227768,
 'knowledge senses': 161243,
 'senses particularly': 266036,
 'particularly scenes': 219898,
 'scenes concerning': 258925,
 'concerning orton': 58456,
 'orton halliwell': 216134,
 'halliwell sets': 132928,
 'sets particularly': 267707,
 'particularly flat': 219840,
 'flat halliwells': 112351,
 'halliwells murals': 132931,
 'murals decorating': 200923,
 'decorating every': 70497,
 'every surface': 94595,
 'surface terribly': 292893,
 'terribly well': 298504,
 'well done': 329410,
 'wonderful little production': 334859,
 'little production filming': 172580,
 'production filming technique': 235231,
 'filming technique unassuming': 108732,
 'technique unassuming oldtimebbc': 297078,
 'unassuming oldtimebbc fashion': 314969,
 'oldtimebbc fashion gives': 212090,
 'fashion gives comforting': 102052,
 'gives comforting sometimes': 123927,
 'comforting sometimes discomforting': 56251,
 'sometimes discomforting sense': 278818,
 'discomforting sense realism': 76958,
 'sense realism entire': 265936,
 'realism entire piece': 242350,
 'entire piece actors': 90413,
 'piece actors extremely': 225460,
 'actors extremely well': 5993,
 'extremely well chosen': 98597,
 'well chosen michael': 329335,
 'chosen michael sheen': 51067,
 'michael sheen got': 188957,
 'sheen got polari': 269247,
 'got polari voices': 128319,
 'polari voices pat': 229814,
 'voices pat truly': 322956,
 'pat truly see': 220544,
 'truly see seamless': 311814,
 'see seamless editing': 263155,
 'seamless editing guided': 261502,
 'editing guided references': 84785,
 'guided references williams': 131447,
 'references williams diary': 245358,
 'williams diary entries': 332657,
 'diary entries well': 74137,
 'entries well worth': 90589,
 'well worth watching': 330088,
 'worth watching terrificly': 337595,
 'watching terrificly written': 327224,
 'terrificly written performed': 298583,
 'written performed piece': 339560,
 'performed piece masterful': 223379,
 'piece masterful production': 225553,
 'masterful production one': 184426,
 'production one great': 235275,
 'one great masters': 213063,
 'great masters comedy': 129706,
 'masters comedy life': 184550,
 'comedy life realism': 55721,
 'life realism really': 168197,
 'realism really comes': 242358,
 'really comes home': 242917,
 'comes home little': 56063,
 'home little things': 140633,
 'little things fantasy': 172685,
 'things fantasy guard': 301126,
 'fantasy guard rather': 101563,
 'guard rather use': 131153,
 'rather use traditional': 240929,
 'use traditional dream': 318630,
 'traditional dream techniques': 309522,
 'dream techniques remains': 81597,
 'techniques remains solid': 297099,
 'remains solid disappears': 246895,
 'solid disappears plays': 277792,
 'disappears plays knowledge': 76555,
 'plays knowledge senses': 227769,
 'knowledge senses particularly': 161244,
 'senses particularly scenes': 266037,
 'particularly scenes concerning': 219899,
 'scenes concerning orton': 258926,
 'concerning orton halliwell': 58457,
 'orton halliwell sets': 216135,
 'halliwell sets particularly': 132929,
 'sets particularly flat': 267708,
 'particularly flat halliwells': 219841,
 'flat halliwells murals': 112352,
 'halliwells murals decorating': 132932,
 'murals decorating every': 200924,
 'decorating every surface': 70498,
 'every surface terribly': 94596,
 'surface terribly well': 292894,
 'terribly well done': 298505,
 'thought': 303105,
 'way': 327468,
 'spend': 281512,
 'time': 304815,
 'hot': 142315,
 'summer': 291690,
 'weekend': 328967,
 'sitting': 274776,
 'air': 9521,
 'conditioned': 58644,
 'theater': 299395,
 'lighthearted': 168679,
 'plot': 228226,
 'simplistic': 273455,
 'dialogue': 73888,
 'witty': 334022,
 'characters': 48113,
 'likable': 168797,
 'even': 92287,
 'bread': 37435,
 'suspected': 293583,
 'serial': 266654,
 'killer': 159292,
 'may': 185179,
 'disappointed': 76565,
 'realize': 242609,
 'match': 184598,
 'point': 229250,
 'risk': 251706,
 'addiction': 7427,
 'proof': 235980,
 'woody': 335317,
 'allen': 10474,
 'still': 285387,
 'fully': 117470,
 'control': 60385,
 'style': 290004,
 'many': 182744,
 'us': 317996,
 'grown': 130979,
 'lovethis': 177386,
 'id': 145084,
 'laughed': 164111,
 'woodys': 335340,
 'comedies': 55506,
 'years': 340443,
 'dare': 67644,
 'say': 257123,
 'decade': 69916,
 'ive': 153871,
 'never': 204905,
 'impressed': 147648,
 'scarlet': 258049,
 'johanson': 155812,
 'managed': 182265,
 'tone': 307610,
 'sexy': 268458,
 'image': 146657,
 'jumped': 157147,
 'right': 251073,
 'average': 22704,
 'spirited': 281837,
 'young': 341706,
 'womanthis': 334478,
 'crown': 65659,
 'jewel': 155207,
 'career': 43420,
 'wittier': 334013,
 'devil': 73624,
 'wears': 328760,
 'prada': 232110,
 'interesting': 151220,
 'superman': 292074,
 'go': 124595,
 'friends': 116608,
 'thought wonderful': 303402,
 'wonderful way': 334948,
 'way spend': 328160,
 'spend time': 281538,
 'time hot': 305199,
 'hot summer': 142394,
 'summer weekend': 291716,
 'weekend sitting': 328984,
 'sitting air': 274777,
 'air conditioned': 9541,
 'conditioned theater': 58647,
 'theater watching': 299484,
 'watching lighthearted': 327037,
 'lighthearted comedy': 168680,
 'comedy plot': 55769,
 'plot simplistic': 228768,
 'simplistic dialogue': 273456,
 'dialogue witty': 74034,
 'witty characters': 334025,
 'characters likable': 48506,
 'likable even': 168811,
 'even well': 93470,
 'well bread': 329296,
 'bread suspected': 37440,
 'suspected serial': 293588,
 'serial killer': 266669,
 'killer may': 159371,
 'may disappointed': 185256,
 'disappointed realize': 76644,
 'realize match': 242633,
 'match point': 184619,
 'point risk': 229478,
 'risk addiction': 251707,
 'addiction thought': 7432,
 'thought proof': 303321,
 'proof woody': 236007,
 'woody allen': 335318,
 'allen still': 10514,
 'still fully': 285562,
 'fully control': 117481,
 'control style': 60411,
 'style many': 290082,
 'many us': 183322,
 'us grown': 318150,
 'grown lovethis': 130988,
 'lovethis id': 177387,
 'id laughed': 145145,
 'laughed one': 164155,
 'one woodys': 214280,
 'woodys comedies': 335341,
 'comedies years': 55560,
 'years dare': 340562,
 'dare say': 67655,
 'say decade': 257223,
 'decade ive': 69924,
 'ive never': 153927,
 'never impressed': 205185,
 'impressed scarlet': 147683,
 'scarlet johanson': 258050,
 'johanson managed': 155817,
 'managed tone': 182312,
 'tone sexy': 307641,
 'sexy image': 268483,
 'image jumped': 146678,
 'jumped right': 157150,
 'right average': 251107,
 'average spirited': 22758,
 'spirited young': 281846,
 'young womanthis': 342034,
 'womanthis may': 334479,
 'may crown': 185248,
 'crown jewel': 65660,
 'jewel career': 155212,
 'career wittier': 43490,
 'wittier devil': 334014,
 'devil wears': 73638,
 'wears prada': 328769,
 'prada interesting': 232111,
 'interesting superman': 151459,
 'superman great': 292085,
 'great comedy': 129408,
 'comedy go': 55679,
 'go see': 124974,
 'see friends': 262628,
 'thought wonderful way': 303405,
 'wonderful way spend': 334950,
 'way spend time': 328163,
 'spend time hot': 281539,
 'time hot summer': 305200,
 'hot summer weekend': 142395,
 'summer weekend sitting': 291717,
 'weekend sitting air': 328985,
 'sitting air conditioned': 274778,
 'air conditioned theater': 9542,
 'conditioned theater watching': 58648,
 'theater watching lighthearted': 299486,
 'watching lighthearted comedy': 327038,
 'lighthearted comedy plot': 168681,
 'comedy plot simplistic': 55770,
 'plot simplistic dialogue': 228769,
 'simplistic dialogue witty': 273457,
 'dialogue witty characters': 74035,
 'witty characters likable': 334026,
 'characters likable even': 48507,
 'likable even well': 168812,
 'even well bread': 93471,
 'well bread suspected': 329297,
 'bread suspected serial': 37441,
 'suspected serial killer': 293589,
 'serial killer may': 266677,
 'killer may disappointed': 159372,
 'may disappointed realize': 185257,
 'disappointed realize match': 76645,
 'realize match point': 242634,
 'match point risk': 184620,
 'point risk addiction': 229479,
 'risk addiction thought': 251708,
 'addiction thought proof': 7433,
 'thought proof woody': 303322,
 'proof woody allen': 236008,
 'woody allen still': 335326,
 'allen still fully': 10515,
 'still fully control': 285563,
 'fully control style': 117482,
 'control style many': 60412,
 'style many us': 290083,
 'many us grown': 183323,
 'us grown lovethis': 318151,
 'grown lovethis id': 130989,
 'lovethis id laughed': 177388,
 'id laughed one': 145146,
 'laughed one woodys': 164156,
 'one woodys comedies': 214281,
 'woodys comedies years': 335342,
 'comedies years dare': 55561,
 'years dare say': 340563,
 'dare say decade': 67657,
 'say decade ive': 257224,
 'decade ive never': 69925,
 'ive never impressed': 153930,
 'never impressed scarlet': 205186,
 'impressed scarlet johanson': 147684,
 'scarlet johanson managed': 258051,
 'johanson managed tone': 155818,
 'managed tone sexy': 182313,
 'tone sexy image': 307642,
 'sexy image jumped': 268484,
 'image jumped right': 146679,
 'jumped right average': 157151,
 'right average spirited': 251108,
 'average spirited young': 22759,
 'spirited young womanthis': 281847,
 'young womanthis may': 342035,
 'womanthis may crown': 334480,
 'may crown jewel': 185249,
 'crown jewel career': 65661,
 'jewel career wittier': 155213,
 'career wittier devil': 43491,
 'wittier devil wears': 334015,
 'devil wears prada': 73639,
 'wears prada interesting': 328770,
 'prada interesting superman': 232112,
 'interesting superman great': 151460,
 'superman great comedy': 292086,
 'great comedy go': 129409,
 'comedy go see': 55680,
 'go see friends': 124979,
 'basically': 26782,
 'theres': 299988,
 'family': 100542,
 'boy': 36703,
 'jake': 154343,
 'thinks': 302281,
 'zombie': 342789,
 'closet': 53755,
 'parents': 218884,
 'fighting': 104924,
 'timethis': 306301,
 'movie': 194647,
 'slower': 276301,
 'soap': 277236,
 'opera': 214991,
 'suddenly': 291127,
 'decides': 70305,
 'become': 28019,
 'rambo': 239972,
 'kill': 159051,
 'zombieok': 342863,
 'first': 111106,
 'youre': 342136,
 'going': 125673,
 'make': 179961,
 'film': 105271,
 'must': 201747,
 'decide': 70156,
 'thriller': 303916,
 'drama': 81080,
 'watchable': 326537,
 'divorcing': 78216,
 'arguing': 18779,
 'like': 168845,
 'real': 241830,
 'totally': 308509,
 'ruins': 254540,
 'expected': 97223,
 'boogeyman': 35221,
 'similar': 273184,
 'instead': 150289,
 'watched': 326575,
 'meaningless': 186288,
 'spots3': 282389,
 '10': 15,
 'playing': 227471,
 'descent': 72241,
 'dialogs': 73870,
 'shots': 270805,
 'ignore': 145864,
 'basically theres': 26868,
 'theres family': 300074,
 'family little': 100708,
 'little boy': 172142,
 'boy jake': 36768,
 'jake thinks': 154353,
 'thinks theres': 302320,
 'theres zombie': 300243,
 'zombie closet': 342798,
 'closet parents': 53760,
 'parents fighting': 218919,
 'fighting timethis': 104959,
 'timethis movie': 306306,
 'movie slower': 197467,
 'slower soap': 276304,
 'soap opera': 277239,
 'opera suddenly': 215018,
 'suddenly jake': 291160,
 'jake decides': 154346,
 'decides become': 70308,
 'become rambo': 28140,
 'rambo kill': 239973,
 'kill zombieok': 159180,
 'zombieok first': 342864,
 'first youre': 111816,
 'youre going': 342188,
 'going make': 125899,
 'make film': 180159,
 'film must': 107189,
 'must decide': 201804,
 'decide thriller': 70197,
 'thriller drama': 303933,
 'drama drama': 81129,
 'drama movie': 81192,
 'movie watchable': 198048,
 'watchable parents': 326553,
 'parents divorcing': 218910,
 'divorcing arguing': 78217,
 'arguing like': 18780,
 'like real': 170180,
 'real life': 242048,
 'life jake': 168055,
 'jake closet': 154344,
 'closet totally': 53766,
 'totally ruins': 308635,
 'ruins film': 254547,
 'film expected': 106257,
 'expected see': 97276,
 'see boogeyman': 262338,
 'boogeyman similar': 35222,
 'similar movie': 273232,
 'movie instead': 196198,
 'instead watched': 150486,
 'watched drama': 326620,
 'drama meaningless': 81190,
 'meaningless thriller': 186297,
 'thriller spots3': 303981,
 'spots3 10': 282390,
 '10 well': 174,
 'well playing': 329813,
 'playing parents': 227583,
 'parents descent': 218906,
 'descent dialogs': 72246,
 'dialogs shots': 73879,
 'shots jake': 270851,
 'jake ignore': 154350,
 'basically theres family': 26869,
 'theres family little': 300075,
 'family little boy': 100710,
 'little boy jake': 172150,
 'boy jake thinks': 36769,
 'jake thinks theres': 154354,
 'thinks theres zombie': 302322,
 'theres zombie closet': 300244,
 'zombie closet parents': 342799,
 'closet parents fighting': 53761,
 'parents fighting timethis': 218920,
 'fighting timethis movie': 104960,
 'timethis movie slower': 306307,
 'movie slower soap': 197468,
 'slower soap opera': 276305,
 'soap opera suddenly': 277243,
 'opera suddenly jake': 215019,
 'suddenly jake decides': 291161,
 'jake decides become': 154347,
 'decides become rambo': 70309,
 'become rambo kill': 28141,
 'rambo kill zombieok': 239974,
 'kill zombieok first': 159181,
 'zombieok first youre': 342865,
 'first youre going': 111817,
 'youre going make': 342192,
 'going make film': 125900,
 'make film must': 180164,
 'film must decide': 107191,
 'must decide thriller': 201805,
 'decide thriller drama': 70198,
 'thriller drama drama': 303934,
 'drama drama movie': 81130,
 'drama movie watchable': 81193,
 'movie watchable parents': 198049,
 'watchable parents divorcing': 326554,
 'parents divorcing arguing': 218911,
 'divorcing arguing like': 78218,
 'arguing like real': 18781,
 'like real life': 170181,
 'real life jake': 242066,
 'life jake closet': 168056,
 'jake closet totally': 154345,
 'closet totally ruins': 53767,
 'totally ruins film': 308636,
 'ruins film expected': 254548,
 'film expected see': 106258,
 'expected see boogeyman': 97277,
 'see boogeyman similar': 262339,
 'boogeyman similar movie': 35223,
 'similar movie instead': 273233,
 'movie instead watched': 196200,
 'instead watched drama': 150487,
 'watched drama meaningless': 326621,
 'drama meaningless thriller': 81191,
 'meaningless thriller spots3': 186298,
 'thriller spots3 10': 303982,
 'spots3 10 well': 282391,
 '10 well playing': 175,
 'well playing parents': 329814,
 'playing parents descent': 227584,
 'parents descent dialogs': 218907,
 'descent dialogs shots': 72247,
 'dialogs shots jake': 73880,
 'shots jake ignore': 270852,
 'petter': 224472,
 'matteis': 184857,
 'love': 176427,
 'money': 192722,
 'visually': 322644,
 'stunning': 289595,
 'watch': 325865,
 'mr': 199429,
 'mattei': 184848,
 'offers': 210763,
 'vivid': 322732,
 'portrait': 230863,
 'human': 143697,
 'relations': 246079,
 'seems': 264129,
 'telling': 297698,
 'power': 231831,
 'success': 290801,
 'people': 221512,
 'different': 74876,
 'situations': 274908,
 'encounter': 87471,
 'variation': 319938,
 'arthur': 19837,
 'schnitzlers': 259591,
 'play': 226881,
 'theme': 299619,
 'director': 75883,
 'transfers': 309961,
 'action': 5289,
 'present': 232957,
 'new': 205577,
 'york': 341427,
 'meet': 186791,
 'connect': 59063,
 'connected': 59090,
 'another': 15737,
 'next': 206132,
 'person': 223843,
 'know': 160566,
 'previous': 233688,
 'contact': 59768,
 'stylishly': 290181,
 'sophisticated': 279608,
 'luxurious': 178071,
 'look': 174273,
 'taken': 295112,
 'live': 172781,
 'world': 336473,
 'habitatthe': 132374,
 'thing': 300598,
 'gets': 121905,
 'souls': 280073,
 'picture': 225215,
 'stages': 282817,
 'loneliness': 173785,
 'inhabits': 149473,
 'big': 31734,
 'city': 51928,
 'exactly': 95660,
 'best': 30230,
 'place': 226158,
 'find': 110012,
 'sincere': 274099,
 'fulfillment': 117257,
 'discerns': 76915,
 'case': 44349,
 'encounterthe': 87519,
 'acting': 4671,
 'good': 126391,
 'direction': 75701,
 'steve': 285145,
 'buscemi': 40332,
 'rosario': 253838,
 'dawson': 68458,
 'carol': 43793,
 'kane': 157491,
 'imperioli': 147283,
 'adrian': 7926,
 'grenier': 130375,
 'rest': 249033,
 'talented': 295743,
 'cast': 44674,
 'come': 55104,
 'alivewe': 10417,
 'wish': 333249,
 'luck': 177722,
 'await': 22920,
 'anxiously': 16535,
 'work': 335645,
 'petter matteis': 224473,
 'matteis love': 184860,
 'love time': 176927,
 'time money': 305334,
 'money visually': 192922,
 'visually stunning': 322674,
 'stunning film': 289607,
 'film watch': 108352,
 'watch mr': 326255,
 'mr mattei': 199500,
 'mattei offers': 184853,
 'offers us': 210799,
 'us vivid': 318392,
 'vivid portrait': 322745,
 'portrait human': 230866,
 'human relations': 143849,
 'relations movie': 246098,
 'movie seems': 197350,
 'seems telling': 264425,
 'telling us': 297741,
 'us money': 318230,
 'money power': 192874,
 'power success': 231899,
 'success people': 290848,
 'people different': 221707,

In [72]:
print(tfi.idf_)
print(tfi.get_feature_names_out())

[7.62007321 7.62007321 7.62007321 ... 7.62007321 7.62007321 7.62007321]
['007' '007 debut' '007 debut goldeneyethis' ... 'ísnt'
 'ísnt entertaining' 'ísnt entertaining wanna']

In [79]:
np.count_nonzero(tfibow[0])

242

In [80]:
feature_names = tfi.get_feature_names_out()
row = tfibow[0]

nonzero_idx = row.nonzero()[0]
for i in nonzero_idx[:10]:
    print(feature_names[i], row[i])

actors 0.02705571845986676
actors extremely 0.0698413172197721
actors extremely well 0.0698413172197721
chosen 0.05977205314909973
chosen michael 0.0698413172197721
chosen michael sheen 0.0698413172197721
comedy 0.031303462912696284
comedy life 0.0698413172197721
comedy life realism 0.0698413172197721
comes 0.03123531806985882